[project]
name = "argentinc"
version = "0.1.0"
description = "Argentinean Agents"
readme = "README.md"
requires-python = ">=3.14.2"
dependencies = []

[dependency-groups]
dev = ["ipykernel>=7.1.0", "pytest>=9.0.2", "ruff>=0.14.14", "ipykernel>=7.1.0"]
